import Head from 'next/head'
import Image from 'next/image'
import Navbar from './component/navbar'
import styles from '@/styles/Home.module.css'
import HeroSection from './component/HeroSection'
import ChoseSection from './component/ChoseSection'
import OurClass from './component/OurClass'
import PricingSection from './component/PricingSection'
import BannerSection from './component/BannerSection'
import TeamSection from './component/TeamSection'
import FooterSection from './component/FooterSection'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Navbar/>
   <HeroSection/>
   <ChoseSection/>
   <OurClass/>
   <BannerSection/>
   <PricingSection/>
   <TeamSection/>
   <FooterSection/>
    </>
  )
}
